name: Bicep Build
author: Aliencube Community
description: Build ARM templates using the bicep CLI

branding:
  icon: copy
  color: orange

inputs:
  files:
    description: List of .bicep files to build, delimited by a space. eg) file1 file2 file3 ...
    required: true
  version:
    description: Version of the bicep CLI. It can be the exact version (eg. `v0.3.255`), wildcard (eg. `v0.3.x`) or `latest`. If omitted, `latest` is set as default.
    required: false
    default: 'latest'
  exitOnFailure:
    description: Exits with bicep CLI exit code if the build fails on a file. If omitted, `false` is set as default.
    required: false
    default: $false

runs:
  using: docker
  image: Dockerfile
  args:
  - -Files
  - ${{ inputs.files }}
  - -Version
  - ${{ inputs.version }}
  - -ExitOnFailure
  - ${{ inputs.exitOnFailure }}
